// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXyUNds7SaXOmS3RNeiJoK8LxSFxiJgpY',
    appId: '1:454348386247:web:251c55947e6697bfb933e2',
    messagingSenderId: '454348386247',
    projectId: 'novels-destiny',
    authDomain: 'novels-destiny.firebaseapp.com',
    storageBucket: 'novels-destiny.firebasestorage.app',
    measurementId: 'G-X26H4D7TK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpb3ST28ugjwzHLpN1O-5j2NmdvkErumc',
    appId: '1:454348386247:android:b27e1f4003a1ddf5b933e2',
    messagingSenderId: '454348386247',
    projectId: 'novels-destiny',
    storageBucket: 'novels-destiny.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnlR3AAJB1ShDqINxLdvlgiJF4mYWHn34',
    appId: '1:454348386247:ios:e07c7168242a64b0b933e2',
    messagingSenderId: '454348386247',
    projectId: 'novels-destiny',
    storageBucket: 'novels-destiny.firebasestorage.app',
    iosBundleId: 'com.example.novelsDestiny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnlR3AAJB1ShDqINxLdvlgiJF4mYWHn34',
    appId: '1:454348386247:ios:e07c7168242a64b0b933e2',
    messagingSenderId: '454348386247',
    projectId: 'novels-destiny',
    storageBucket: 'novels-destiny.firebasestorage.app',
    iosBundleId: 'com.example.novelsDestiny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXyUNds7SaXOmS3RNeiJoK8LxSFxiJgpY',
    appId: '1:454348386247:web:e0a033db33366170b933e2',
    messagingSenderId: '454348386247',
    projectId: 'novels-destiny',
    authDomain: 'novels-destiny.firebaseapp.com',
    storageBucket: 'novels-destiny.firebasestorage.app',
    measurementId: 'G-BP7Y5X6J19',
  );
}
